# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - composer install
              -  ./vendor/bin/phpunit test
            caches:
              - composer
        - step:
            name: Lint
            script:
              - composer install
              - ./vendor/bin/phplint . --exclude=vendor
            caches:
              - composer
        - step:
            name: Deploy
            script:
              - pipe: atlassian/sftp-deploy:0.5.11
                variables:
                  USER: "root"
                  SERVER: "159.203.15.162"
                  REMOTE_PATH: "/var/www/html"
                  PASSWORD: "formY5@project"