version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:3q3PZoCGaMtf9BLKjPrWQmRvAEl/G/nY+0n6lLl2nRQ=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./datadump.sql:/docker-entrypoint-initdb.d/datadump.sql 
    networks:
    - app-network
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
networks:
  app-network:
    driver: bridge